---
title: "Figure_invitro"
output: html_notebook
---



```{r setup, include=FALSE}
library(tidyverse)
library(ggrepel)
library(cowplot)
library(clusterProfiler)
library(ggtext)
library(org.Mm.eg.db)
```

# Direct target assignments focusing on in vitro data.

Idea is to get the direct targets assignments using only in vitro data.

# Read datasets

```{r echo = FALSE,warning = FALSE,message = FALSE, error = FALSE}
# # Npeaks data
# knockdown_genes_zic1_npeaks <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic1_npeaks.tsv")
# knockdown_genes_zic2_npeaks <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic2_npeaks.tsv")
# 
# knockdown_genes_zic1_npeaks_in_vitro <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic1_npeaks_in_vitro.tsv")
# knockdown_genes_zic2_npeaks_in_vitro <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic2_npeaks_in_vitro")
# 
# knockdown_genes_zic1_npeaks_dir <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic1_npeaks_dir.tsv")
# knockdown_genes_zic2_npeaks_dir <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic2_npeaks_dir.tsv")
# 
# knockdown_genes_zic1_npeaks_in_vitro_dir <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic1_npeaks_in_vitro_dir.tsv")
# knockdown_genes_zic2_npeaks_in_vitro_dir <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic2_npeaks_in_vitro_dir.tsv")
# 
# knockdown_genes_zic1_npeaks_dir_zic_dependent <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic1_npeaks_in_vitro_dir.tsv")
# knockdown_genes_zic2_npeaks_dir_zic_dependent <- read_tsv("../results/invitro/figure_invitro/knockdown_genes_zic2_npeaks_in_vitro_dir.tsv")
# 
# 
# # GO data
# zic1_comp_go <- readRDS("../results/invitro/figure_invitro/zic1_comp_go.Rds")
# zic2_comp_go <- readRDS("../results/invitro/figure_invitro/zic2_comp_go.Rds")


invitro_data = read_tsv("../results/FinalTables/invitro_table.txt")
go_results =  load("../results/invitro/figure_invitro/go_cat.RData")

```



# Plots

Zic1 log2FC vs number of in vitro peaks
```{r, fig.height=8, fig.width=12}
a = invitro_data %>% 
  dplyr::select( gene_names, dev_log2foldchange, dev_padj,  zic_peak, num_peaks) %>% 
  distinct() %>% 
  dplyr::select(-zic_peak) %>% 
  dplyr::mutate(dev_sig = ifelse(abs(dev_log2foldchange) >=2 & dev_padj < 0.05, "sig", "ns")) %>% 
  distinct() %>%
  ggplot(aes( x= num_peaks, y = dev_log2foldchange, label = gene_names, color = dev_sig)) +
  geom_point(alpha = 0.5, size = 1) +
  scale_color_manual(values = c("grey40", "black"))+
  geom_text_repel() +
  theme_bw() +
  xlab("Number of mapped invitro Zic peaks") +
  ylab("GE log2(DIV7 / DIV3)")


b = invitro_data %>% 
  dplyr::select(id, gene_names, log2foldchange, padj, zic_peak, num_peaks) %>% 
  distinct() %>% 
  dplyr::select(-zic_peak) %>% 
  dplyr::mutate(kd_sig = ifelse(abs(log2foldchange) >=2 & padj < 0.05, "sig", "ns")) %>% 
  distinct() %>% 
  ggplot(aes( x= num_peaks, y = log2foldchange, label = gene_names, color = kd_sig)) +
  geom_point(alpha = 0.3, size = 1) +
  scale_color_manual(values = c("grey40", "black"))+
  geom_text_repel()+
  theme_bw() +
  facet_wrap(~id)+
  xlab("Number of mapped invitro Zic peaks") +
  ylab("GE log2(KD / Ctrl DIV7)")

plot_grid(a,b, ncol = 1)

```



Zic1 KD/Ctrl vs D7/D3 


```{r, fig.height=8, fig.width=12}
c = invitro_data %>% 
  dplyr::select(zic_peak, id, dev_log2foldchange,log2foldchange,gene_names, bothKD, cat, num_peaks ) %>% 
  distinct() %>% 
  dplyr::select(-zic_peak) %>% 
  distinct() %>% 
  ggplot(aes( x = dev_log2foldchange, y = log2foldchange, label = gene_names, color = bothKD, size = num_peaks)) +
  geom_point(alpha = 0.5) +
  geom_text_repel(size = 5, min.segment.length = unit(5, "cm"), max.overlaps = 20)+
  facet_grid(id~cat) +
  theme_bw() +
  scale_color_manual(values = c("#143589", "#E1BE6A", "#40B0A6"), limits =  c("Zic1 KD", "Zic2 KD", "Zic1 & Zic2 KD"))+
  theme(legend.position = "bottom",
        strip.background = element_rect(fill = "black"),
        strip.text = element_text(color = "white"))+
  labs(x = "GE log2(DIV7 / DIV3)", y = "GE log2(Zic1/2 KD / Ctrl)", color = "KD", size = "no. mapped peaks" )

c

```
```{r}
invitro_data %>% 
  dplyr::select(gene_names,cat) %>% 
  distinct() %>% 
  group_by(cat) %>% 
  dplyr::count()
```




```{r, fig.width= 6, fig.height=8}


# d1 = dotplot(g_bp) + 
#   theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# 
# cnetplot(g_mf)
# cnetplot(g_bp)
# cnetplot(g_cc)
# 
# cnetplot(g_cat_mf)
# cnetplot(g_cat_bp)
# cnetplot(g_cat_cc)
# 
# cnetplot(zdd_t_mf)
# cnetplot(zdd_t_bp)
# cnetplot(zdd_t_cc)
# 
# 
# 
# dotplot(g_cat_bp) + theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# dotplot(g_bp) + 
#   theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# dotplot(g_mf) + 
#   theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# dotplot(g_cc) + 
#   theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# dotplot(g_cat_mf) + theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# dotplot(g_cat_cc) + theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# dotplot(zdd_t_bp) + theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 
# 
# dotplot(zdd_t_cc) + theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11, angle = 45, hjust  = 1)) + 
#   scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
#   scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) 

d1 = dotplot(zdd_t_bp) + 
  theme(axis.text.y = element_text(size = 11), axis.text.x = element_text(size =11)) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 25)) +
  scale_x_discrete( labels = str_wrap(c("Fail to Up-regulate", "Fail to Down-regulate"), width = 15)) +
  scale_color_viridis_c(option = "magma")

d2 = cnetplot(zdd_t_bp, showCategory = 5, color_gene = "green", cex_label_gene = 1.25, cex_label_category = 1.6, layout = "fr") + 
  scale_fill_grey(limits = c("Up", "Down"), labels = c("Fail to Up-regulate", "Fail to Down-regulate")) 

d2

plot_grid(d1, d2, ncol = 1)


 
  
```






Adding in vitro n peaks

```{r, fig.height=12, fig.width=8}


  
plt_dat = invitro_data %>% 
  # select data
  dplyr::select(ends_with(c("hange", "adj")),  zic_peak, gene_names, bothKD, cat , num_peaks, dev_sig, zic_sig) %>% 
  distinct() %>% 
  # color genes by affected KD 
  dplyr::mutate(gene_labels = case_when(bothKD == "Zic1 KD" ~ paste0('<span style="color:#143589">', gene_names,'</span>' ),
                                       bothKD == "Zic2 KD" ~ paste0('<span style="color:#E1BE6A">', gene_names,'</span>' ),
                                       bothKD == "Zic1 & Zic2 KD" ~ paste0('<span style="color: #40B0A6">', gene_names,'</span>' ))) %>% 

  dplyr::mutate(gene_names = fct_reorder(gene_names, num_peaks)) %>%
  dplyr::mutate(gene_labels = fct_reorder(gene_labels, num_peaks)) %>%
  # filter for plot
  dplyr::select(gene_names,gene_labels, zic_peak, num_peaks, ends_with("sig"), cat) %>% 
  distinct() %>% 
  #dplyr::filter(num_peaks > 20) %>%
  dplyr::filter(dev_sig != "N.S.") %>%
  drop_na(zic_peak) 

e_leg = get_legend(plt_dat %>% 
  dplyr::filter(cat == "Developmental") %>% 
  # plot
  ggplot(aes(y = gene_labels, fill =zic_sig))+
  geom_bar(stat = "count") +
  facet_grid(dev_sig~cat, scales = "free", space = "free")+
  scale_fill_manual(values = c("Up"="#D81B60","Down"="#1E88E5","Static" ="gray")) +
  theme_classic() + 
  labs(y = "Gene Symbol", x = "# Zic Peaks Mapped to Gene", fill = "DIV7/DIV3") +
  theme(axis.text.y = element_markdown(),
        axis.text.x = element_markdown(size = 8), 
        legend.position = "bottom",
         #legend.justification = c("right", "top"),
         legend.box.just = "right",
         legend.margin = margin(2, 2, 2, 2),
         #legend.box.background = element_rect(color="black", size=1),
         legend.text = element_text(size = 11),
         legend.key.size = unit(.5, "lines"),
         legend.title = element_text(size = 11, face = "bold"),
        strip.background = element_rect(fill = "black"),
        strip.text = element_text(color = "white")))

e1 = plt_dat %>% 
  dplyr::filter(cat == "Developmental") %>% 
  # plot
  ggplot(aes(y = gene_labels, fill =zic_sig))+
  geom_bar(stat = "count") +
  facet_grid(dev_sig~cat, scales = "free", space = "free")+
  scale_fill_manual(values = c("Up"="#D81B60","Down"="#1E88E5","Static" ="gray")) +
  theme_classic() + 
  labs(y = "Gene Symbol", x = "# Zic Peaks Mapped to Gene", fill = "DIV7/DIV3") +
  theme(axis.text.y = element_markdown(),
        axis.text.x = element_markdown(size = 8), 
        legend.position = "none",
        strip.background = element_rect(fill = "black"),
        strip.text = element_text(color = "white"))

e2 = plt_dat %>% 
  dplyr::filter(cat == "Zic Dependent Developmental") %>% 
  # plot
  ggplot(aes(y = gene_labels, fill =zic_sig))+
  geom_bar(stat = "count") +
  facet_grid(dev_sig~cat, scales = "free", space = "free", labeller = labeller(dev_sig = c("Down" = "Fail to Down-regulate", "Up"="Fail to Up-regulate")))+
  scale_fill_manual(values = c("Up"="#D81B60","Down"="#1E88E5","Static" ="gray")) +
  theme_classic() + 
  labs(y = "", x = "# Zic Peaks Mapped to Gene", fill = "DIV7/DIV3") +
  theme(axis.text.y = element_markdown(),
        axis.text.x = element_markdown(size = 8), 
        legend.position = "none",
        strip.background = element_rect(fill = "black"),
        strip.text = element_text(color = "white"))
      
      

e = plot_grid(plot_grid(e1, e2),
              e_leg,ncol = 1,
              rel_heights = c(.95,.05))
  
e
```
```{r}
plt_dat %>% 
  dplyr::select(gene_names, cat) %>% 
  distinct() %>% 
  group_by(cat) %>% 
  dplyr::count()
```

```{r, fig.width=12, fig.height=15}
d = plot_grid(d1, d2, labels = c("C", "D"), ncol =1)
fig4 = plot_grid(c,
          plot_grid(e2, d,ncol = 2, rel_widths = c(1,1), labels = c("B", "")),
          ncol =1,
          rel_heights = c(.4, .6),
          labels = "A")


png("../figures/figure4.png", height = 15, width = 12, res = 300, units = "in")
fig4
dev.off()

```
